spring.application.name=backend
server.port=9098

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ToDoAppdb}
spring.datasource.username=${DB_USERNAME:user}
spring.datasource.password=${DB_PASSWORD:my_very_strongPassword#}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET:change_this_secret_key_change_this_secret_key_123456}
app.jwt.expiration-ms=900000
app.security.max-failed-attempts=5
app.security.lock-duration-minutes=1
app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:4200}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:fodorean50@gmail.com}
spring.mail.password=${MAIL_PASSWORD:toie buiq lycb xdjx}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mfa.issuer=ToDoApp
app.mfa.otp-expiry-minutes=10